# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 13, 11, 21, 304978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='balance',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
