# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of this service'),
        ),
    ]
