# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='service',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='user',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
