# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170809_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='new', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 6, 36, 49, 229866, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together=set([('service', 'user')]),
        ),
    ]
