# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import facecontrol.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('video', models.FileField(upload_to=facecontrol.models.user_directory_path)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
