# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170702_0744'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
