# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20170611_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(upload_to='badge_images', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.CharField(choices=[('1', 'Bronze'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Diamond')], max_length=1, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='user',
            field=models.ManyToManyField(related_name='badges', through='badges.BadgeToUser', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
