# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_auto_20170711_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetouser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
