# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=55, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=55, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=55, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=55, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=55, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=55, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=55, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='description')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typology.Action', verbose_name='action')),
            ],
        ),
        migrations.CreateModel(
            name='TypologyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True, verbose_name='slug')),
                ('name', models.CharField(max_length=55, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=55, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=55, null=True, verbose_name='description')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typology.Action', verbose_name='action')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typology.Brand', verbose_name='brand')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typology.Subject', verbose_name='subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='typology.Subject', verbose_name='subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('name', 'action')]),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('name', 'subject')]),
        ),
    ]
