# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
