# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170718_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='user',
            new_name='created_by',
        ),
    ]
