# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 05:00
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170711_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('executant', 'Executant'), ('client', 'Client')], max_length=30, null=True),
        ),
    ]
