# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170711_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
