# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_performer',
            field=models.BooleanField(default=False),
        ),
    ]
