# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=36, null=True)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=15, null=True)),
                ('state', django_fsm.FSMField(choices=[('new', 'New'), ('accepted', 'Accepted')], default='new', max_length=50, protected=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
    ]
